'use client';

import { useState, useMemo, useEffect } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import {
  Select, SelectContent, SelectItem, SelectTrigger, SelectValue,
} from "@/components/ui/select";
import {
  Command, CommandEmpty, CommandGroup, CommandInput, CommandItem, CommandList,
} from "@/components/ui/command";
import { Separator } from "@/components/ui/separator";
import { Badge } from "@/components/ui/badge";
import { Plus, Trash2, ChevronsUpDown, AlertTriangle } from "lucide-react";
import { useVendorStore } from "./vendorStore";
import { PurchaseOrderItem, POPriority, VENDOR_CATEGORY_LABELS } from "./types";
import { useInventoryStore } from "../inventory/inventoryStore";
import { inventoryDisplayLabel } from "../inventory/itemLabel";
import { useToast } from "@/hooks/use-toast";
import { cn } from "@/lib/utils";

interface PurchaseOrderFormProps {
  branchId: string;
  onSuccess: () => void;
  onCancel: () => void;
  /** When set, the form edits that PO in place instead of creating a new one. */
  poId?: string | null;
}

interface LineItem {
  inventory_item_id: string | null; // linked inventory item id
  item_name: string;
  description: string;
  quantity: string;
  unit: string;
  unit_price: string;
}

// Generate a unique PO number: PO-YYYYMMDD-XXXX
function generatePONumber(): string {
  const now = new Date();
  const date = now.toISOString().slice(0, 10).replace(/-/g, '');
  const rand = Math.floor(1000 + Math.random() * 9000);
  return `PO-${date}-${rand}`;
}

// The label is generated by the shared helper so that goods receipt can resolve
// a legacy line back to its inventory item. A private copy here would drift and
// silently stop matching.

export function PurchaseOrderForm({ branchId, onSuccess, onCancel, poId }: PurchaseOrderFormProps) {
  const { vendors, purchaseOrders, createPurchaseOrder, updatePurchaseOrder } = useVendorStore();
  const inventoryItems = useInventoryStore(s => s.items);
  const fetchItems = useInventoryStore(s => s.fetchItems);
  const { toast } = useToast();
  const [isSubmitting, setIsSubmitting] = useState(false);

  // The PO being edited, if any. It is already in the store because this form is
  // only ever opened from the list/detail view, which render from that same store.
  const existingPO = poId ? purchaseOrders.find(p => p.id === poId) ?? null : null;
  const isEditing = !!existingPO;

  // Ensure inventory is loaded for this branch
  useEffect(() => {
    fetchItems(branchId);
  }, [branchId, fetchItems]);

  // Close any open combobox when clicking outside
  useEffect(() => {
    const handler = () => setOpenCombo({});
    document.addEventListener('mousedown', handler);
    return () => document.removeEventListener('mousedown', handler);
  }, []);

  // Stable PO number for this form session. When editing we keep the existing
  // number — it is the identifier Accounts and the vendor already reference.
  const [poNumber] = useState(() => existingPO?.po_number ?? generatePONumber());

  const [formData, setFormData] = useState(() => ({
    vendor_id: existingPO?.vendor_id ?? '',
    description: existingPO?.description ?? '',
    priority: (existingPO?.priority ?? 'normal') as POPriority,
    expected_delivery: existingPO?.expected_delivery ?? '',
  }));

  // The inventory link is now persisted, so an edited line keeps the item it
  // restocks instead of degrading to free text.
  const [items, setItems] = useState<LineItem[]>(() =>
    existingPO?.items?.length
      ? existingPO.items.map(item => ({
          inventory_item_id: item.inventory_item_id ?? null,
          item_name: item.item_name,
          description: item.description ?? '',
          quantity: String(item.quantity),
          unit: item.unit,
          unit_price: String(item.unit_price),
        }))
      : [{ inventory_item_id: null, item_name: '', description: '', quantity: '1', unit: 'pcs', unit_price: '' }]
  );

  const [errors, setErrors] = useState<Record<string, string>>({});
  // Track open state per line item combobox
  const [openCombo, setOpenCombo] = useState<Record<number, boolean>>({});

  const activeVendors = vendors.filter(v => v.status === 'active');
  const selectedVendor = activeVendors.find(v => v.id === formData.vendor_id);

  // Inventory items for this branch, sorted by name
  const branchInventory = useMemo(() =>
    inventoryItems
      .filter(i => i.branch === branchId)
      .sort((a, b) => a.name.localeCompare(b.name)),
    [inventoryItems, branchId]
  );

  const addItem = () => {
    setItems(prev => [...prev, { inventory_item_id: null, item_name: '', description: '', quantity: '1', unit: 'pcs', unit_price: '' }]);
  };

  const removeItem = (index: number) => {
    if (items.length <= 1) return;
    setItems(items.filter((_, i) => i !== index));
  };

  const updateItem = (index: number, field: keyof LineItem, value: string | null) => {
    const updated = [...items];
    updated[index] = { ...updated[index], [field]: value ?? '' };
    setItems(updated);
  };

  const selectInventoryItem = (lineIndex: number, invItemId: string) => {
    const inv = branchInventory.find(i => i.id === invItemId);
    if (!inv) return;
    const updated = [...items];
    updated[lineIndex] = {
      ...updated[lineIndex],
      inventory_item_id: inv.id,
      item_name: inventoryDisplayLabel(inv),   // meaningful label, not raw name
      unit: inv.unitOfMeasure || 'pcs',
      unit_price: inv.purchasePrice?.toString() || '',
    };
    setItems(updated);
    setOpenCombo(prev => ({ ...prev, [lineIndex]: false }));
    // Clear errors for this row
    setErrors(prev => {
      const next = { ...prev };
      delete next[`item_${lineIndex}_name`];
      delete next[`item_${lineIndex}_price`];
      return next;
    });
  };

  const getItemTotal = (item: LineItem): number => {
    const qty = parseFloat(item.quantity) || 0;
    const price = parseFloat(item.unit_price) || 0;
    return qty * price;
  };

  const subtotal = items.reduce((sum, item) => sum + getItemTotal(item), 0);
  const taxAmount = subtotal * 0.18;
  const grandTotal = subtotal + taxAmount;

  const validate = (): boolean => {
    const newErrors: Record<string, string> = {};
    if (!formData.vendor_id) newErrors.vendor_id = 'Please select a vendor';
    let hasItemError = false;
    items.forEach((item, idx) => {
      if (!item.item_name.trim()) { newErrors[`item_${idx}_name`] = 'Item name required'; hasItemError = true; }
      if (!item.quantity || parseFloat(item.quantity) <= 0) { newErrors[`item_${idx}_qty`] = 'Invalid quantity'; hasItemError = true; }
      if (!item.unit_price || parseFloat(item.unit_price) <= 0) { newErrors[`item_${idx}_price`] = 'Invalid price'; hasItemError = true; }
    });
    if (hasItemError) newErrors.items = 'Please fix item errors';
    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!validate()) return;
    setIsSubmitting(true);

    const poItems: PurchaseOrderItem[] = items.map(item => ({
      // Carry the inventory link through to the DB. It used to be captured in form
      // state and then dropped here, which left receiving with no item to credit.
      inventory_item_id: item.inventory_item_id || null,
      item_name: item.item_name.trim(),
      description: item.description.trim() || undefined,
      quantity: parseInt(item.quantity),
      unit: item.unit,
      unit_price: parseFloat(item.unit_price),
      total_price: getItemTotal(item),
    }));

    const result = isEditing && existingPO
      ? await updatePurchaseOrder(existingPO.id, {
          vendor_id: formData.vendor_id,
          vendor_name: selectedVendor?.name || '',
          vendor_category: selectedVendor?.category || 'other',
          description: formData.description.trim() || undefined,
          items: poItems,
          priority: formData.priority,
          expected_delivery: formData.expected_delivery || undefined,
        })
      : await createPurchaseOrder({
          vendor_id: formData.vendor_id,
          vendor_name: selectedVendor?.name || '',
          vendor_category: selectedVendor?.category || 'other',
          title: poNumber,         // PO number is now the title/identifier
          description: formData.description.trim() || undefined,
          items: poItems,
          priority: formData.priority,
          expected_delivery: formData.expected_delivery || undefined,
          branch_id: branchId,
          created_by: 'admin',
        });

    setIsSubmitting(false);

    if (result.success) {
      toast(isEditing
        ? { title: "Purchase Order Updated", description: `${poNumber} has been saved.` }
        : { title: "Purchase Order Created", description: `${poNumber} has been created as draft.` });
      onSuccess();
    } else {
      toast({
        title: "Error",
        description: result.error || `Failed to ${isEditing ? 'update' : 'create'} purchase order`,
        variant: "destructive",
      });
    }
  };

  return (
    <form onSubmit={handleSubmit} className="space-y-5">

      {/* ── Header row: PO number + Vendor + Priority + Delivery ── */}
      <div className="space-y-3">
        {/* PO Number badge */}
        <div className="flex items-center gap-3">
          <span className="text-xs text-muted-foreground uppercase tracking-wide font-semibold">PO Number</span>
          <Badge variant="outline" className="font-mono text-sm px-3 py-1 tracking-wide">{poNumber}</Badge>
          <span className="text-xs text-muted-foreground">
            {isEditing
              ? 'Existing PO · totals are recalculated from the line items on save'
              : 'Auto-generated · saved as draft on creation'}
          </span>
        </div>

        {/* 4-col row: Vendor (2) + Priority (1) + Delivery (1) */}
        <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
          <div className="space-y-2 md:col-span-2">
            <Label htmlFor="vendor_id">Vendor *</Label>
            <Select value={formData.vendor_id} onValueChange={v => {
              setFormData(prev => ({ ...prev, vendor_id: v }));
              if (errors.vendor_id) setErrors(prev => ({ ...prev, vendor_id: '' }));
            }}>
              <SelectTrigger className={errors.vendor_id ? 'border-destructive' : ''}>
                <SelectValue placeholder="Select a vendor" />
              </SelectTrigger>
              <SelectContent>
                {activeVendors.length === 0 ? (
                  <SelectItem value="none" disabled>No active vendors — add one first</SelectItem>
                ) : activeVendors.map(vendor => (
                  <SelectItem key={vendor.id} value={vendor.id}>
                    <span>{vendor.name}</span>
                    <span className="ml-2 text-xs text-muted-foreground">({VENDOR_CATEGORY_LABELS[vendor.category]})</span>
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
            {errors.vendor_id && <p className="text-xs text-destructive">{errors.vendor_id}</p>}
          </div>

          <div className="space-y-2">
            <Label>Priority</Label>
            <Select value={formData.priority} onValueChange={v => setFormData(prev => ({ ...prev, priority: v as POPriority }))}>
              <SelectTrigger><SelectValue /></SelectTrigger>
              <SelectContent>
                <SelectItem value="low">Low</SelectItem>
                <SelectItem value="normal">Normal</SelectItem>
                <SelectItem value="high">High</SelectItem>
                <SelectItem value="urgent">Urgent</SelectItem>
              </SelectContent>
            </Select>
          </div>

          <div className="space-y-2">
            <Label htmlFor="expected_delivery">Expected Delivery</Label>
            <Input id="expected_delivery" type="date" value={formData.expected_delivery}
              onChange={e => setFormData(prev => ({ ...prev, expected_delivery: e.target.value }))} />
          </div>
        </div>

        {/* Description — full width, compact */}
        <div className="space-y-1.5">
          <Label htmlFor="description" className="text-xs">Description <span className="text-muted-foreground font-normal">(optional)</span></Label>
          <Textarea id="description" value={formData.description}
            onChange={e => setFormData(prev => ({ ...prev, description: e.target.value }))}
            placeholder="Brief notes about this purchase order..."
            rows={1}
            className="resize-none" />
        </div>
      </div>

      <Separator />

      {/* ── Line Items ── */}
      <div className="space-y-3">
        <div className="flex items-center justify-between">
          <h3 className="text-xs font-semibold text-muted-foreground uppercase tracking-wide">Line Items</h3>
          <Button type="button" variant="outline" size="sm" onClick={addItem}>
            <Plus className="h-4 w-4 mr-1" /> Add Item
          </Button>
        </div>
        {errors.items && <p className="text-xs text-destructive">{errors.items}</p>}

        {/* Column headers */}
        <div className="grid grid-cols-[1fr_80px_80px_120px_100px_36px] gap-3 px-3 pb-1 border-b">
          <span className="text-xs font-medium text-muted-foreground">Item</span>
          <span className="text-xs font-medium text-muted-foreground">Qty</span>
          <span className="text-xs font-medium text-muted-foreground">Unit</span>
          <span className="text-xs font-medium text-muted-foreground">Unit Price (₹)</span>
          <span className="text-xs font-medium text-muted-foreground text-right">Total</span>
          <span />
        </div>

        <div className="space-y-2">
          {items.map((item, index) => {
            const linkedInv = item.inventory_item_id
              ? branchInventory.find(i => i.id === item.inventory_item_id)
              : null;
            const isLow = linkedInv && linkedInv.currentStock <= linkedInv.reorderLevel;

            return (
              <div key={index} className="space-y-1">
                {/* Single flat row */}
                <div className="grid grid-cols-[1fr_80px_80px_120px_100px_36px] gap-3 items-center">
                  {/* Item combobox — inline dropdown, no portal */}
                  <div className="relative">
                    <Button
                      type="button"
                      variant="outline"
                      role="combobox"
                      onClick={() => setOpenCombo(prev => ({ ...prev, [index]: !prev[index] }))}
                      className={cn("w-full justify-between font-normal h-9 text-sm",
                        errors[`item_${index}_name`] && "border-destructive",
                        !item.item_name && "text-muted-foreground"
                      )}
                    >
                      <span className="truncate">{item.item_name || "Select from inventory…"}</span>
                      <ChevronsUpDown className="ml-2 h-3.5 w-3.5 shrink-0 opacity-50" />
                    </Button>

                    {openCombo[index] && (
                      <div
                        className="absolute left-0 top-full mt-1 z-500 w-full min-w-[380px] rounded-lg border bg-popover shadow-xl"
                        onMouseDown={e => e.stopPropagation()}
                      >
                        <Command>
                          <CommandInput placeholder="Search inventory items…" />
                          <CommandList className="max-h-[240px]" style={{ overflowY: 'auto' }}>
                            <CommandEmpty>No items found.</CommandEmpty>
                            <CommandGroup>
                              {branchInventory.map(inv => (
                                <CommandItem
                                  key={inv.id}
                                  value={`${inventoryDisplayLabel(inv)} ${inv.itemCode} ${inv.name}`}
                                  onSelect={() => selectInventoryItem(index, inv.id)}
                                  className="cursor-pointer data-[selected=true]:bg-muted data-[selected=true]:text-foreground"
                                >
                                  <div className="flex items-center justify-between w-full gap-2">
                                    <div className="flex flex-col min-w-0">
                                      <span className="truncate font-medium text-sm">{inventoryDisplayLabel(inv)}</span>
                                      <span className="text-xs text-muted-foreground font-mono">
                                        {inv.itemCode}{inv.name ? ` · ${inv.name}` : ''}
                                      </span>
                                    </div>
                                    <div className="flex items-center gap-1.5 shrink-0">
                                      {inv.currentStock <= inv.reorderLevel && (
                                        <AlertTriangle className="h-3 w-3 text-amber-500" />
                                      )}
                                      <span className={cn("text-xs", inv.currentStock <= inv.reorderLevel ? "text-amber-600 font-semibold" : "text-muted-foreground")}>
                                        {inv.currentStock} in stock
                                      </span>
                                    </div>
                                  </div>
                                </CommandItem>
                              ))}
                            </CommandGroup>
                          </CommandList>
                        </Command>
                      </div>
                    )}
                    {errors[`item_${index}_name`] && <p className="text-xs text-destructive mt-0.5">{errors[`item_${index}_name`]}</p>}
                  </div>

                  {/* Qty */}
                  <Input type="number" min="1" value={item.quantity}
                    onChange={e => updateItem(index, 'quantity', e.target.value)}
                    className={cn("h-9", errors[`item_${index}_qty`] && "border-destructive")} />

                  {/* Unit */}
                  <Select value={item.unit} onValueChange={v => updateItem(index, 'unit', v)}>
                    <SelectTrigger className="h-9"><SelectValue /></SelectTrigger>
                    <SelectContent>
                      <SelectItem value="pcs">Pcs</SelectItem>
                      <SelectItem value="pairs">Pairs</SelectItem>
                      <SelectItem value="kg">Kg</SelectItem>
                      <SelectItem value="ltr">Ltr</SelectItem>
                      <SelectItem value="box">Box</SelectItem>
                      <SelectItem value="set">Set</SelectItem>
                      <SelectItem value="month">Month</SelectItem>
                    </SelectContent>
                  </Select>

                  {/* Unit Price */}
                  <Input type="number" min="0" step="0.01" value={item.unit_price}
                    onChange={e => updateItem(index, 'unit_price', e.target.value)}
                    placeholder="0.00"
                    className={cn("h-9", errors[`item_${index}_price`] && "border-destructive")} />

                  {/* Total */}
                  <div className="h-9 flex items-center justify-end px-3 bg-muted rounded-md text-sm font-medium">
                    ₹{getItemTotal(item).toLocaleString()}
                  </div>

                  {/* Delete */}
                  <Button type="button" variant="ghost" size="icon"
                    className="h-9 w-9 text-destructive hover:text-destructive"
                    onClick={() => removeItem(index)} disabled={items.length <= 1}>
                    <Trash2 className="h-4 w-4" />
                  </Button>
                </div>

                {/* Stock hint */}
                {linkedInv && (
                  <div className={cn("flex items-center gap-1.5 text-xs pl-1", isLow ? "text-amber-600" : "text-muted-foreground")}>
                    {isLow && <AlertTriangle className="h-3 w-3 shrink-0" />}
                    <span>
                      Stock: <strong>{linkedInv.currentStock}</strong> {linkedInv.unitOfMeasure}
                      {' · '}Reorder: <strong>{linkedInv.reorderLevel}</strong>
                      {isLow && ' · ⚠ Below reorder level'}
                    </span>
                  </div>
                )}
              </div>
            );
          })}
        </div>
      </div>

      <Separator />

      {/* ── Totals ── */}
      <div className="flex justify-end">
        <div className="w-full max-w-xs space-y-2">
          <div className="flex justify-between text-sm">
            <span className="text-muted-foreground">Subtotal</span>
            <span>₹{subtotal.toLocaleString()}</span>
          </div>
          <div className="flex justify-between text-sm">
            <span className="text-muted-foreground">GST (18%)</span>
            <span>₹{taxAmount.toLocaleString()}</span>
          </div>
          <Separator />
          <div className="flex justify-between font-semibold">
            <span>Grand Total</span>
            <span>₹{grandTotal.toLocaleString()}</span>
          </div>
        </div>
      </div>

      {/* ── Actions ── */}
      <div className="flex justify-end gap-3 pt-2">
        <Button type="button" variant="outline" onClick={onCancel} disabled={isSubmitting}>Cancel</Button>
        <Button type="submit" disabled={isSubmitting}>
          {isSubmitting
            ? (isEditing ? 'Saving...' : 'Creating...')
            : (isEditing ? 'Save Changes' : 'Create Purchase Order')}
        </Button>
      </div>
    </form>
  );
}
