'use client';

/**
 * Print / PDF view for the audit log.
 *
 * Printing the live table would produce a document of whatever 20 rows happened
 * to be on screen, with the surrounding application chrome, filter controls and
 * sidebar rendered into the page — and with every truncated cell still truncated,
 * because `text-overflow: ellipsis` prints exactly as it displays.
 *
 * This is a separate document instead:
 *
 *   - It covers the ENTIRE filtered result set, fetched page by page, not the
 *     page on screen.
 *   - Values print in full. No truncation, no ellipses, no tooltips — anything
 *     only reachable by hovering is unprintable by definition, so the field-level
 *     changes are laid out inline.
 *   - It carries a cover block recording who printed it, when, and exactly which
 *     filters were in effect, so a printout is self-describing months later.
 *   - Page numbers, repeated table headers, and controlled page breaks come from
 *     the print stylesheet in `audit-print.css`.
 *
 * "Save as PDF" in the browser's print dialog produces the PDF version, which
 * avoids shipping a second rendering engine to every admin who never prints.
 */

import { Fragment, useEffect } from 'react';
import type { AuditRecord } from '@/lib/audit/types';

export interface PrintFilterSummary {
  label: string;
  value: string;
}

interface AuditPrintViewProps {
  records: readonly AuditRecord[];
  filters: readonly PrintFilterSummary[];
  /** Total matching the filters, which may exceed the exported cap. */
  totalMatching: number;
  printedBy: string;
  /** Called once the browser print dialog has been dismissed. */
  onAfterPrint: () => void;
  /** Include the field-change breakdown under each entry. */
  includeChanges: boolean;
  /** Include the device/network block under each entry. */
  includeContext: boolean;
}

function formatTimestamp(iso: string): string {
  return new Date(iso).toLocaleString('en-IN', {
    day: '2-digit', month: 'short', year: 'numeric',
    hour: '2-digit', minute: '2-digit', second: '2-digit', hour12: true,
  });
}

export function AuditPrintView({
  records,
  filters,
  totalMatching,
  printedBy,
  onAfterPrint,
  includeChanges,
  includeContext,
}: AuditPrintViewProps) {
  useEffect(() => {
    // Wait for layout and font loading before opening the dialog, otherwise the
    // first page can be measured against unstyled text and break in the wrong
    // place.
    const start = window.setTimeout(() => window.print(), 250);

    const handleAfterPrint = () => onAfterPrint();
    window.addEventListener('afterprint', handleAfterPrint);

    return () => {
      window.clearTimeout(start);
      window.removeEventListener('afterprint', handleAfterPrint);
    };
  }, [onAfterPrint]);

  const truncated = totalMatching > records.length;

  return (
    <div className="audit-print-root" role="document" aria-label="Audit log printout">
      {/* ── Cover block ──────────────────────────────────────────────────── */}
      <header className="audit-print-cover">
        <h1>Activity &amp; Audit Log</h1>
        <p className="audit-print-subtitle">Safend ERP — forensic activity record</p>

        <table className="audit-print-meta">
          <tbody>
            <tr>
              <th scope="row">Generated</th>
              <td>
                {new Date().toLocaleString('en-IN', {
                  day: '2-digit', month: 'long', year: 'numeric',
                  hour: '2-digit', minute: '2-digit', hour12: true,
                })}
              </td>
            </tr>
            <tr>
              <th scope="row">Generated by</th>
              <td>{printedBy}</td>
            </tr>
            <tr>
              <th scope="row">Records in this document</th>
              <td>
                {records.length.toLocaleString('en-IN')}
                {truncated && (
                  <>
                    {' '}of {totalMatching.toLocaleString('en-IN')} matching
                    <strong> (capped)</strong>
                  </>
                )}
              </td>
            </tr>
            <tr>
              <th scope="row">Filters applied</th>
              <td>
                {filters.length === 0 ? (
                  <em>None — all records</em>
                ) : (
                  <ul className="audit-print-filters">
                    {filters.map((f) => (
                      <li key={f.label}>
                        <strong>{f.label}:</strong> {f.value}
                      </li>
                    ))}
                  </ul>
                )}
              </td>
            </tr>
          </tbody>
        </table>

        {truncated && (
          <p className="audit-print-warning">
            This document was capped at {records.length.toLocaleString('en-IN')} records.
            Narrow the date range or filters to produce a complete printout of all{' '}
            {totalMatching.toLocaleString('en-IN')} matching entries.
          </p>
        )}

        <p className="audit-print-note">
          Timestamps are shown in India Standard Time. Each entry carries an integrity
          hash computed by the database when the record was written; the audit table
          permits no updates or deletes from any application client.
        </p>
      </header>

      {/* ── Entries ──────────────────────────────────────────────────────── */}
      <table className="audit-print-table">
        <thead>
          <tr>
            <th scope="col" style={{ width: '4%' }}>#</th>
            <th scope="col" style={{ width: '15%' }}>Timestamp</th>
            <th scope="col" style={{ width: '17%' }}>User</th>
            <th scope="col" style={{ width: '15%' }}>Action</th>
            <th scope="col" style={{ width: '19%' }}>Target</th>
            <th scope="col" style={{ width: '11%' }}>Module</th>
            <th scope="col" style={{ width: '8%' }}>Outcome</th>
            <th scope="col" style={{ width: '11%' }}>IP</th>
          </tr>
        </thead>
        <tbody>
          {records.map((record, index) => (
            <Fragment key={record.id}>
              <tr className="audit-print-row">
                <td className="audit-print-num">{index + 1}</td>
                <td>{formatTimestamp(record.timestamp)}</td>
                <td>
                  {record.actorName}
                  <br />
                  <span className="audit-print-dim">{record.actorEmail}</span>
                </td>
                <td>
                  {record.action}
                  <br />
                  <span className="audit-print-dim">{record.severity}</span>
                </td>
                <td>{record.target}</td>
                <td>{record.module}</td>
                <td className={`audit-print-outcome-${record.outcome}`}>{record.outcome}</td>
                <td className="audit-print-mono">
                  {record.ip}
                  {record.location && (
                    <>
                      <br />
                      <span className="audit-print-dim">{record.location}</span>
                    </>
                  )}
                </td>
              </tr>

              {includeChanges && record.changes.length > 0 && (
                <tr className="audit-print-detail">
                  <td />
                  <td colSpan={7}>
                    <p className="audit-print-detail-heading">
                      Field changes ({record.changes.length})
                    </p>
                    <table className="audit-print-changes">
                      <thead>
                        <tr>
                          <th scope="col">Field</th>
                          <th scope="col">Before</th>
                          <th scope="col">After</th>
                        </tr>
                      </thead>
                      <tbody>
                        {record.changes.map((change, i) => (
                          <tr key={`${change.path}-${i}`}>
                            <td>{change.label}</td>
                            <td className="audit-print-mono">
                              {change.before === null || change.before === undefined
                                ? '—'
                                : String(change.before)}
                            </td>
                            <td className="audit-print-mono">
                              {change.after === null || change.after === undefined
                                ? '—'
                                : String(change.after)}
                            </td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </td>
                </tr>
              )}

              {includeContext && (
                <tr className="audit-print-detail">
                  <td />
                  <td colSpan={7}>
                    <p className="audit-print-context">
                      {[
                        record.os && `Device: ${record.os} · ${record.browser ?? 'unknown browser'}`,
                        record.deviceType && `Form factor: ${record.deviceType}`,
                        record.route && `Route: ${record.route}`,
                        record.durationMs !== null && record.durationMs !== undefined &&
                          `Duration: ${record.durationMs} ms`,
                        record.branchName && `Branch: ${record.branchName}`,
                        record.actorRoles.length > 0 && `Roles: ${record.actorRoles.join(', ')}`,
                        record.sessionId && `Session: ${record.sessionId}`,
                        record.uiState?.heading && `Screen: ${record.uiState.heading}`,
                        record.errorMessage && `Error: ${record.errorMessage}`,
                        record.hasSnapshot && 'Visual snapshot on file',
                      ]
                        .filter(Boolean)
                        .join('  ·  ')}
                    </p>
                    {Object.keys(record.details).length > 0 && (
                      <p className="audit-print-context">
                        Details: {JSON.stringify(record.details)}
                      </p>
                    )}
                    <p className="audit-print-hash">
                      Record {record.id}
                      {record.entryHash && ` · hash ${record.entryHash}`}
                    </p>
                  </td>
                </tr>
              )}
            </Fragment>
          ))}
        </tbody>
      </table>

      <footer className="audit-print-footer">
        End of report — {records.length.toLocaleString('en-IN')} entries.
      </footer>
    </div>
  );
}
