/**
 * Canonical payable categories — single source of truth for the app side.
 *
 * These 9 MECE buckets replaced the original 10 loosely-defined ones
 * (Salary, EPF/ESIC, Taxes, Vendor Payment, Purchase, House Rent,
 * Reimbursement, Credit Notes, Auxiliary Expense, Mess Expense).
 *
 * IMPORTANT: this list is mirrored by the `payables_category_check` CHECK
 * constraint in the database. Adding or renaming a value here without shipping
 * a matching migration produces a runtime insert failure:
 *
 *   new row for relation "payables" violates check constraint
 *   "payables_category_check"
 *
 * See:
 *   supabase/migrations/20260711000000_consolidate_payable_categories.sql
 *   supabase/migrations/20260801000000_fix_payables_category_check.sql
 */
export const PAYABLE_CATEGORIES = [
  'Salary & Wages',
  'EPF & ESIC',
  'Statutory & Taxes',
  'Vendor & Supplies',
  'Rent & Utilities',
  'Reimbursements',
  'Mess Expense',
  'Compliance & Licenses',
  'Other Expenses',
] as const;

export type PayableCategory = (typeof PAYABLE_CATEGORIES)[number];

/** Filter tab values for the Payables section — categories plus an "All" tab. */
export const PAYABLE_FILTERS = ['All', ...PAYABLE_CATEGORIES] as const;

/**
 * Categories whose entries are generated by other modules (payroll approval,
 * mess fund requests), so the Payables screen shows no "Add Entry" button.
 */
// Typed as readonly string[] because callers test it against the raw `filter`
// prop, which arrives as a plain string from the URL / tab bar.
export const NO_ADD_CATEGORIES: readonly string[] = [
  'Salary & Wages',
  'Mess Expense',
] satisfies readonly PayableCategory[];
