-- =========================================================
-- Server-side timestamp enforcement
-- 
-- Single source of truth: all timestamps are generated by
-- Postgres `now()` rather than client-side `new Date()`.
-- This prevents clock-skew issues from user machines.
-- =========================================================

-- 1) Reusable trigger function for auto-updating `updated_at`
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

-- 2) Trigger function that sets `marked_at` to now() when status changes from 'pending'
CREATE OR REPLACE FUNCTION public.set_marked_at_on_status_change()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  -- Only set marked_at when transitioning away from 'pending' and marked_at is not being explicitly cleared
  IF OLD.status = 'pending' AND NEW.status != 'pending' AND NEW.marked_at IS NULL THEN
    NEW.marked_at = now();
  END IF;
  RETURN NEW;
END;
$$;

-- 3) Trigger function that sets `completed_at` to now() when status becomes 'completed'
CREATE OR REPLACE FUNCTION public.set_completed_at_on_complete()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF NEW.status = 'completed' AND (OLD.status IS DISTINCT FROM 'completed') THEN
    NEW.completed_at = now();
  END IF;
  RETURN NEW;
END;
$$;

-- 4) Trigger function that sets `reviewed_at` to now() when status changes from 'pending'
CREATE OR REPLACE FUNCTION public.set_reviewed_at_on_review()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF OLD.status = 'pending' AND NEW.status IN ('approved', 'rejected') THEN
    NEW.reviewed_at = now();
  END IF;
  RETURN NEW;
END;
$$;

-- =========================================================
-- Apply triggers to tables
-- =========================================================

-- shift_attendance: auto-set marked_at when status changes from pending
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'shift_attendance') THEN
    DROP TRIGGER IF EXISTS trg_shift_attendance_marked_at ON public.shift_attendance;
    CREATE TRIGGER trg_shift_attendance_marked_at
      BEFORE UPDATE ON public.shift_attendance
      FOR EACH ROW
      EXECUTE FUNCTION public.set_marked_at_on_status_change();
  END IF;
END $$;

-- contract_renewals: auto-set updated_at
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'contract_renewals') THEN
    DROP TRIGGER IF EXISTS trg_contract_renewals_updated_at ON public.contract_renewals;
    CREATE TRIGGER trg_contract_renewals_updated_at
      BEFORE UPDATE ON public.contract_renewals
      FOR EACH ROW
      EXECUTE FUNCTION public.set_updated_at();
  END IF;
END $$;

-- pending_tasks: auto-set completed_at when status becomes 'completed'
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'pending_tasks') THEN
    DROP TRIGGER IF EXISTS trg_pending_tasks_completed_at ON public.pending_tasks;
    CREATE TRIGGER trg_pending_tasks_completed_at
      BEFORE UPDATE ON public.pending_tasks
      FOR EACH ROW
      EXECUTE FUNCTION public.set_completed_at_on_complete();
  END IF;
END $$;

-- deletion_requests: auto-set reviewed_at when status changes to approved/rejected
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'deletion_requests') THEN
    DROP TRIGGER IF EXISTS trg_deletion_requests_reviewed_at ON public.deletion_requests;
    CREATE TRIGGER trg_deletion_requests_reviewed_at
      BEFORE UPDATE ON public.deletion_requests
      FOR EACH ROW
      EXECUTE FUNCTION public.set_reviewed_at_on_review();
  END IF;
END $$;

-- payroll_requests: auto-set workflow timestamps based on status transitions
CREATE OR REPLACE FUNCTION public.set_payroll_workflow_timestamps()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  -- Set workflow timestamps based on status transition
  IF NEW.status = 'SENT_TO_ACCOUNTS' AND (OLD.status IS DISTINCT FROM 'SENT_TO_ACCOUNTS') THEN
    NEW.sent_to_accounts_on = now();
  END IF;
  IF NEW.status = 'APPROVED_BY_ACCOUNTS' AND (OLD.status IS DISTINCT FROM 'APPROVED_BY_ACCOUNTS') THEN
    NEW.accounts_approved_on = now();
  END IF;
  IF NEW.status = 'REJECTED_BY_ACCOUNTS' AND (OLD.status IS DISTINCT FROM 'REJECTED_BY_ACCOUNTS') THEN
    NEW.accounts_rejected_on = now();
  END IF;
  IF NEW.status = 'COMPLETED' AND (OLD.status IS DISTINCT FROM 'COMPLETED') THEN
    NEW.processed_on = now();
  END IF;
  RETURN NEW;
END;
$$;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'payroll_requests') THEN
    -- Add updated_at column if it doesn't exist
    IF NOT EXISTS (
      SELECT 1 FROM information_schema.columns 
      WHERE table_schema = 'public' AND table_name = 'payroll_requests' AND column_name = 'updated_at'
    ) THEN
      ALTER TABLE public.payroll_requests ADD COLUMN updated_at timestamptz DEFAULT now();
    END IF;

    DROP TRIGGER IF EXISTS trg_payroll_requests_updated_at ON public.payroll_requests;
    CREATE TRIGGER trg_payroll_requests_updated_at
      BEFORE UPDATE ON public.payroll_requests
      FOR EACH ROW
      EXECUTE FUNCTION public.set_payroll_workflow_timestamps();
  END IF;
END $$;

-- leave_requests: auto-set updated_at on any update
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'leave_requests') THEN
    IF NOT EXISTS (
      SELECT 1 FROM information_schema.columns 
      WHERE table_schema = 'public' AND table_name = 'leave_requests' AND column_name = 'updated_at'
    ) THEN
      ALTER TABLE public.leave_requests ADD COLUMN updated_at timestamptz DEFAULT now();
    END IF;

    DROP TRIGGER IF EXISTS trg_leave_requests_updated_at ON public.leave_requests;
    CREATE TRIGGER trg_leave_requests_updated_at
      BEFORE UPDATE ON public.leave_requests
      FOR EACH ROW
      EXECUTE FUNCTION public.set_updated_at();
  END IF;
END $$;

-- deleted_invoice_numbers: auto-set used_at when is_used becomes true
CREATE OR REPLACE FUNCTION public.set_used_at_on_use()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF NEW.is_used = true AND (OLD.is_used IS DISTINCT FROM true) THEN
    NEW.used_at = now();
  END IF;
  RETURN NEW;
END;
$$;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'deleted_invoice_numbers') THEN
    DROP TRIGGER IF EXISTS trg_deleted_invoice_numbers_used_at ON public.deleted_invoice_numbers;
    CREATE TRIGGER trg_deleted_invoice_numbers_used_at
      BEFORE UPDATE ON public.deleted_invoice_numbers
      FOR EACH ROW
      EXECUTE FUNCTION public.set_used_at_on_use();
  END IF;
END $$;

-- user_sessions: use server time for last_active
-- (handled in app code by removing client timestamp)

-- =========================================================
-- RPC: update_last_active — sets last_active to server now()
-- Called from client instead of passing new Date().toISOString()
-- =========================================================
CREATE OR REPLACE FUNCTION public.update_last_active()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  UPDATE public.users
  SET last_active = now()
  WHERE id = auth.uid();
END;
$$;

GRANT EXECUTE ON FUNCTION public.update_last_active() TO authenticated;

-- =========================================================
-- RPC function: get server time (for client display/sync)
-- =========================================================
CREATE OR REPLACE FUNCTION public.server_now()
RETURNS timestamptz
LANGUAGE sql
STABLE
AS $$
  SELECT now();
$$;

GRANT EXECUTE ON FUNCTION public.server_now() TO authenticated, anon;
